config/routes.rb
Kargod2::Application.routes.draw do
  resources :trims

  resources :models

  resources :makes

  devise_for :users

  resources :users

  root :to => 'static_pages#home'

  post '/get_model_data/:id', to: 'models#get_model_data'

  get '/dealer_dash', to: 'static_pages#dealer_dash'

  get '/user_dash', to: 'static_pages#user_dash'

  get '/user_app', to: 'static_pages#user_app'

end

app/models/make.rb
class Make < ActiveRecord::Base
   attr_accessible :name

   has_many :models

end

app/models/model.rb
class Model < ActiveRecord::Base
   attr_accessible :name, :image, :make_id, :year

   belongs_to :make
   has_many :trims

end

app/models/trim.rb
class Trim < ActiveRecord::Base
   attr_accessible :name, :model_id, :base_msrp, :base_invoice, :tmv, :used_tmv_retail, :used_tmv_pp, :used_tmv_tradein
   
   belongs_to :model
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me


  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_create do |user| 
  		user.provider = auth.provider
  		user.uid = auth.uid
  		user.email = auth.info.email
  		user.name = auth.info.name
  		user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    end
  end

  def self.new_with_session(params, session)
  	if session["devise.user_attributes"]
  		new(session["devise.user_attributes"], without_protection: true) do |user|
  			user.attributes = params
  			user.valid?
  		end
  	else
  		super
  	end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end

  def password_required?
    super && provider.blank?
  end

  def not_facebook
    provider.blank? 
  end

  before_save { |user| user.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :name, presence: true, :on => :create, :if => :not_facebook
  validates :password, presence: true, length: { minimum: 6 }, :on => :create, :if => :not_facebook
  validates_confirmation_of :password, :on => :create, :if => :not_facebook
  validates :password_confirmation, presence: true, :on => :create, :if => :not_facebook


end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  # GET /models
  # GET /models.json

  def get_model_data
    @models = Model.find_all_by_make_id(params[:id]).uniq{|m| m.name}.sort

    respond_to do |format|
      format.js
    end

  end


  def index
    @models = Model.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @models }
    end
  end

  # GET /models/1
  # GET /models/1.json
  def show
    @model = Model.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/new
  # GET /models/new.json
  def new
    @model = Model.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/1/edit
  def edit
    @model = Model.find(params[:id])
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(params[:model])

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render json: @model, status: :created, location: @model }
      else
        format.html { render action: "new" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /models/1
  # PUT /models/1.json
  def update
    @model = Model.find(params[:id])

    respond_to do |format|
      if @model.update_attributes(params[:model])
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model = Model.find(params[:id])
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<%= form_for(@model) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/models/edit.html.erb
<h1>Editing model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

app/views/models/get_model_data.js.erb
$('#model_id').empty();
<% for model in @models %>
	$('#model_id').append($("<option></option>").attr("value",<%= model.id %>).text('<%= model.name %>'));
<% end %>

app/views/models/index.html.erb
<head>
  <%= javascript_include_tag 'initial_search.js' %>
</head>

<body>
  <div class="container" align="center">
    <% makes_array = Make.all.map{ |m| [m.name, m.id, {:class => 'pick_make'}] } %>
    <%= select_tag(:make_id, options_for_select(makes_array, {:class => 'pick_make'})) %>
    <br>
    <% models_array = Model.all.uniq{|m| m.name}.map{ |m| [m.name, m.id, {:class => 'pick_model'}] } %>
    <%= select_tag(:model_id, options_for_select(models_array, {:class => 'pick_model'})) %>
    <br>
    <% start_year_array = [[1990, 1990],[1991, 1991],[1992, 1992],[1993, 1993],[1994, 1994],[1995, 1995],[1996, 1996],[1997, 1997],[1998, 1998],[1999, 1999],[2000, 2000],[2001, 2001],[2002, 2002],[2003, 2003],[2004, 2004],[2005, 2005],[2006, 2006],[2007, 2007],[2008, 2008],[2009, 2009],[2010, 2010],[2011, 2011],[2012, 2012],[2013, 2013 ]] %>
    <%= select_tag(:start_year, options_for_select(start_year_array)) %>
    <% end_year_array = [[1990, 1990],[1991, 1991],[1992, 1992],[1993, 1993],[1994, 1994],[1995, 1995],[1996, 1996],[1997, 1997],[1998, 1998],[1999, 1999],[2000, 2000],[2001, 2001],[2002, 2002],[2003, 2003],[2004, 2004],[2005, 2005],[2006, 2006],[2007, 2007],[2008, 2008],[2009, 2009],[2010, 2010],[2011, 2011],[2012, 2012],[2013, 2013 ]] %>
    <%= select_tag(:end_year, options_for_select(end_year_array)) %>

  </div>
  <script>
    $(document).ready(function() {
      $('#model_id').html("<option value=''>Select Model</option>");
    });
  </script>
</body>

app/views/models/new.html.erb
<h1>New model</h1>

<%= render 'form' %>

<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>