config/routes.rb
Kargod2::Application.routes.draw do
  resources :trims

  resources :models

  resources :makes

  devise_for :users

  resources :users

  root :to => 'static_pages#home'

  post '/get_model_data/:id', to: 'models#get_model_data'

  get '/dealer_dash', to: 'static_pages#dealer_dash'

  get '/user_dash', to: 'static_pages#user_dash'

  get '/user_app', to: 'static_pages#user_app'

end

app/models/trim.rb
class Trim < ActiveRecord::Base
   attr_accessible :name, :model_id, :base_msrp, :base_invoice, :tmv, :used_tmv_retail, :used_tmv_pp, :used_tmv_tradein
   
   belongs_to :model
end

app/controllers/trims_controller.rb
class TrimsController < ApplicationController
  # GET /trims
  # GET /trims.json
  def index
    @trims = Trim.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trims }
    end
  end

  # GET /trims/1
  # GET /trims/1.json
  def show
    @trim = Trim.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trim }
    end
  end

  # GET /trims/new
  # GET /trims/new.json
  def new
    @trim = Trim.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trim }
    end
  end

  # GET /trims/1/edit
  def edit
    @trim = Trim.find(params[:id])
  end

  # POST /trims
  # POST /trims.json
  def create
    @trim = Trim.new(params[:trim])

    respond_to do |format|
      if @trim.save
        format.html { redirect_to @trim, notice: 'Trim was successfully created.' }
        format.json { render json: @trim, status: :created, location: @trim }
      else
        format.html { render action: "new" }
        format.json { render json: @trim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trims/1
  # PUT /trims/1.json
  def update
    @trim = Trim.find(params[:id])

    respond_to do |format|
      if @trim.update_attributes(params[:trim])
        format.html { redirect_to @trim, notice: 'Trim was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trims/1
  # DELETE /trims/1.json
  def destroy
    @trim = Trim.find(params[:id])
    @trim.destroy

    respond_to do |format|
      format.html { redirect_to trims_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trims_helper.rb
module TrimsHelper
end

app/views/trims/_form.html.erb
<%= form_for(@trim) do |f| %>
  <% if @trim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trim.errors.count, "error") %> prohibited this trim from being saved:</h2>

      <ul>
      <% @trim.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trims/edit.html.erb
<h1>Editing trim</h1>

<%= render 'form' %>

<%= link_to 'Show', @trim %> |
<%= link_to 'Back', trims_path %>

app/views/trims/index.html.erb
<h1>Listing trims</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trims.each do |trim| %>
  <tr>
    <td><%= link_to 'Show', trim %></td>
    <td><%= link_to 'Edit', edit_trim_path(trim) %></td>
    <td><%= link_to 'Destroy', trim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trim', new_trim_path %>

app/views/trims/new.html.erb
<h1>New trim</h1>

<%= render 'form' %>

<%= link_to 'Back', trims_path %>

app/views/trims/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_trim_path(@trim) %> |
<%= link_to 'Back', trims_path %>