config/routes.rb
Kargod2::Application.routes.draw do
  resources :trims

  resources :models

  resources :makes

  devise_for :users

  resources :users

  root :to => 'static_pages#home'

  post '/get_model_data/:id', to: 'models#get_model_data'

  get '/dealer_dash', to: 'static_pages#dealer_dash'

  get '/user_dash', to: 'static_pages#user_dash'

  get '/user_app', to: 'static_pages#user_app'

end

app/models/make.rb
class Make < ActiveRecord::Base
   attr_accessible :name

   has_many :models

end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @makes }
    end
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
    @make = Make.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @make }
    end
  end

  # GET /makes/new
  # GET /makes/new.json
  def new
    @make = Make.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @make }
    end
  end

  # GET /makes/1/edit
  def edit
    @make = Make.find(params[:id])
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(params[:make])

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render json: @make, status: :created, location: @make }
      else
        format.html { render action: "new" }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /makes/1
  # PUT /makes/1.json
  def update
    @make = Make.find(params[:id])

    respond_to do |format|
      if @make.update_attributes(params[:make])
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make = Make.find(params[:id])
    @make.destroy

    respond_to do |format|
      format.html { redirect_to makes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/views/makes/_form.html.erb
<%= form_for(@make) do |f| %>
  <% if @make.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@make.errors.count, "error") %> prohibited this make from being saved:</h2>

      <ul>
      <% @make.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/makes/edit.html.erb
<h1>Editing make</h1>

<%= render 'form' %>

<%= link_to 'Show', @make %> |
<%= link_to 'Back', makes_path %>

app/views/makes/index.html.erb
<h1>Listing makes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @makes.each do |make| %>
  <tr>
    <td><%= link_to 'Show', make %></td>
    <td><%= link_to 'Edit', edit_make_path(make) %></td>
    <td><%= link_to 'Destroy', make, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Make', new_make_path %>

app/views/makes/new.html.erb
<h1>New make</h1>

<%= render 'form' %>

<%= link_to 'Back', makes_path %>

app/views/makes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_make_path(@make) %> |
<%= link_to 'Back', makes_path %>